// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecipeCosting.Api.Data;

#nullable disable

namespace RecipeCosting.Api.Data.Migrations
{
    [DbContext(typeof(RecipeCostingDbContext))]
    [Migration("20260906152055_CreateProducts")]
    partial class CreateProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipeCosting.Api.Models.Entities.BakerSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CardFee")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("card_fee");

                    b.Property<decimal>("DaysPerWeek")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("days_per_week");

                    b.Property<decimal>("DefaultMarkup")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("default_markup");

                    b.Property<decimal>("HoursPerDay")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hours_per_day");

                    b.Property<decimal>("MonthlyFixedCosts")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_fixed_costs");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_income");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("tax");

                    b.HasKey("Id");

                    b.ToTable("baker_settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardFee = 3.5m,
                            DaysPerWeek = 5m,
                            DefaultMarkup = 100m,
                            HoursPerDay = 6m,
                            MonthlyFixedCosts = 1250m,
                            MonthlyIncome = 4000m,
                            Tax = 6m
                        });
                });

            modelBuilder.Entity("RecipeCosting.Api.Models.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<decimal>("PackagePrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("package_price");

                    b.Property<decimal>("PackageSize")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("package_size");

                    b.Property<int>("PackageUnit")
                        .HasColumnType("integer")
                        .HasColumnName("package_unit");

                    b.HasKey("Id");

                    b.ToTable("ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Condensed milk",
                            PackagePrice = 7.49m,
                            PackageSize = 395m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Table cream",
                            PackagePrice = 4.29m,
                            PackageSize = 200m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Whole milk",
                            PackagePrice = 5.49m,
                            PackageSize = 1000m,
                            PackageUnit = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cream cheese",
                            PackagePrice = 9.9m,
                            PackageSize = 150m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Whipping cream",
                            PackagePrice = 28.9m,
                            PackageSize = 1000m,
                            PackageUnit = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Unsalted butter",
                            PackagePrice = 12.9m,
                            PackageSize = 200m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Baking margarine",
                            PackagePrice = 9.9m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Vegetable oil",
                            PackagePrice = 8.49m,
                            PackageSize = 900m,
                            PackageUnit = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "All-purpose flour",
                            PackagePrice = 5.79m,
                            PackageSize = 1000m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cornstarch",
                            PackagePrice = 6.49m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cornmeal",
                            PackagePrice = 4.19m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Granulated sugar",
                            PackagePrice = 4.89m,
                            PackageSize = 1000m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Icing sugar",
                            PackagePrice = 5.29m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Brown sugar",
                            PackagePrice = 8.9m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "Glucose syrup",
                            PackagePrice = 12.5m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "Honey",
                            PackagePrice = 18.9m,
                            PackageSize = 250m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "Cocoa powder",
                            PackagePrice = 14.9m,
                            PackageSize = 200m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 18,
                            Name = "Semisweet chocolate",
                            PackagePrice = 42.9m,
                            PackageSize = 1000m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 19,
                            Name = "Milk chocolate",
                            PackagePrice = 44.9m,
                            PackageSize = 1000m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 20,
                            Name = "White chocolate",
                            PackagePrice = 46.5m,
                            PackageSize = 1000m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 21,
                            Name = "Roasted peanuts",
                            PackagePrice = 14.9m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 22,
                            Name = "Walnut halves",
                            PackagePrice = 19.9m,
                            PackageSize = 100m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 23,
                            Name = "Grated coconut",
                            PackagePrice = 6.9m,
                            PackageSize = 100m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 24,
                            Name = "Strawberries",
                            PackagePrice = 12.9m,
                            PackageSize = 300m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 25,
                            Name = "Vanilla extract",
                            PackagePrice = 18.9m,
                            PackageSize = 100m,
                            PackageUnit = 2
                        },
                        new
                        {
                            Id = 26,
                            Name = "Red food colouring",
                            PackagePrice = 7.9m,
                            PackageSize = 30m,
                            PackageUnit = 2
                        },
                        new
                        {
                            Id = 27,
                            Name = "Lemon",
                            PackagePrice = 9.6m,
                            PackageSize = 12m,
                            PackageUnit = 3
                        },
                        new
                        {
                            Id = 28,
                            Name = "Chocolate sprinkles",
                            PackagePrice = 13.9m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 29,
                            Name = "Confetti sprinkles",
                            PackagePrice = 8.4m,
                            PackageSize = 100m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 30,
                            Name = "Eggs",
                            PackagePrice = 24.9m,
                            PackageSize = 30m,
                            PackageUnit = 3
                        },
                        new
                        {
                            Id = 31,
                            Name = "Baking powder",
                            PackagePrice = 4.19m,
                            PackageSize = 100m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 32,
                            Name = "Unflavoured gelatin",
                            PackagePrice = 5.9m,
                            PackageSize = 24m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 33,
                            Name = "Fine salt",
                            PackagePrice = 3.29m,
                            PackageSize = 1000m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 34,
                            Name = "Cupcake liners",
                            PackagePrice = 9.9m,
                            PackageSize = 100m,
                            PackageUnit = 3
                        },
                        new
                        {
                            Id = 35,
                            Name = "Cake box 20 cm",
                            PackagePrice = 24.0m,
                            PackageSize = 10m,
                            PackageUnit = 3
                        });
                });

            modelBuilder.Entity("RecipeCosting.Api.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Markup")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("markup");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<decimal>("PrepMinutes")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("prep_minutes");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Brigadeiro",
                            PrepMinutes = 2m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beijinho",
                            PrepMinutes = 2m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chocolate truffle",
                            PrepMinutes = 3m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chocolate bonbon",
                            PrepMinutes = 4m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Brownie",
                            PrepMinutes = 4m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cupcake",
                            PrepMinutes = 5m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chocolate cake slice",
                            PrepMinutes = 6m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cheesecake slice",
                            PrepMinutes = 8m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Banoffee jar",
                            PrepMinutes = 10m
                        },
                        new
                        {
                            Id = 10,
                            Markup = 90m,
                            Name = "Strawberry tart",
                            PrepMinutes = 12m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Coconut candy box",
                            PrepMinutes = 25m
                        },
                        new
                        {
                            Id = 12,
                            Markup = 80m,
                            Name = "Carrot cake with fudge",
                            PrepMinutes = 45m
                        },
                        new
                        {
                            Id = 13,
                            Markup = 90m,
                            Name = "Lemon pie",
                            PrepMinutes = 60m
                        },
                        new
                        {
                            Id = 14,
                            Markup = 120m,
                            Name = "Red velvet cake 20 cm",
                            PrepMinutes = 90m
                        },
                        new
                        {
                            Id = 15,
                            Markup = 150m,
                            Name = "Wedding cake tier",
                            PrepMinutes = 180m
                        });
                });

            modelBuilder.Entity("RecipeCosting.Api.Models.Entities.ProductLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_lines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 1,
                            ProductId = 1,
                            Quantity = 18m
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 17,
                            ProductId = 1,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 6,
                            ProductId = 1,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 4,
                            IngredientId = 28,
                            ProductId = 1,
                            Quantity = 4m
                        },
                        new
                        {
                            Id = 5,
                            IngredientId = 1,
                            ProductId = 2,
                            Quantity = 18m
                        },
                        new
                        {
                            Id = 6,
                            IngredientId = 23,
                            ProductId = 2,
                            Quantity = 6m
                        },
                        new
                        {
                            Id = 7,
                            IngredientId = 6,
                            ProductId = 2,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 8,
                            IngredientId = 18,
                            ProductId = 3,
                            Quantity = 12m
                        },
                        new
                        {
                            Id = 9,
                            IngredientId = 5,
                            ProductId = 3,
                            Quantity = 6m
                        },
                        new
                        {
                            Id = 10,
                            IngredientId = 6,
                            ProductId = 3,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 11,
                            IngredientId = 19,
                            ProductId = 4,
                            Quantity = 15m
                        },
                        new
                        {
                            Id = 12,
                            IngredientId = 1,
                            ProductId = 4,
                            Quantity = 8m
                        },
                        new
                        {
                            Id = 13,
                            IngredientId = 6,
                            ProductId = 4,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 14,
                            IngredientId = 18,
                            ProductId = 5,
                            Quantity = 15m
                        },
                        new
                        {
                            Id = 15,
                            IngredientId = 6,
                            ProductId = 5,
                            Quantity = 12m
                        },
                        new
                        {
                            Id = 16,
                            IngredientId = 12,
                            ProductId = 5,
                            Quantity = 20m
                        },
                        new
                        {
                            Id = 17,
                            IngredientId = 9,
                            ProductId = 5,
                            Quantity = 12m
                        },
                        new
                        {
                            Id = 18,
                            IngredientId = 17,
                            ProductId = 5,
                            Quantity = 5m
                        },
                        new
                        {
                            Id = 19,
                            IngredientId = 30,
                            ProductId = 5,
                            Quantity = 0.3m
                        },
                        new
                        {
                            Id = 20,
                            IngredientId = 9,
                            ProductId = 6,
                            Quantity = 30m
                        },
                        new
                        {
                            Id = 21,
                            IngredientId = 12,
                            ProductId = 6,
                            Quantity = 25m
                        },
                        new
                        {
                            Id = 22,
                            IngredientId = 6,
                            ProductId = 6,
                            Quantity = 15m
                        },
                        new
                        {
                            Id = 23,
                            IngredientId = 30,
                            ProductId = 6,
                            Quantity = 0.5m
                        },
                        new
                        {
                            Id = 24,
                            IngredientId = 3,
                            ProductId = 6,
                            Quantity = 20m
                        },
                        new
                        {
                            Id = 25,
                            IngredientId = 31,
                            ProductId = 6,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 26,
                            IngredientId = 34,
                            ProductId = 6,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 27,
                            IngredientId = 29,
                            ProductId = 6,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 28,
                            IngredientId = 9,
                            ProductId = 7,
                            Quantity = 25m
                        },
                        new
                        {
                            Id = 29,
                            IngredientId = 12,
                            ProductId = 7,
                            Quantity = 30m
                        },
                        new
                        {
                            Id = 30,
                            IngredientId = 17,
                            ProductId = 7,
                            Quantity = 8m
                        },
                        new
                        {
                            Id = 31,
                            IngredientId = 30,
                            ProductId = 7,
                            Quantity = 0.5m
                        },
                        new
                        {
                            Id = 32,
                            IngredientId = 8,
                            ProductId = 7,
                            Quantity = 15m
                        },
                        new
                        {
                            Id = 33,
                            IngredientId = 3,
                            ProductId = 7,
                            Quantity = 25m
                        },
                        new
                        {
                            Id = 34,
                            IngredientId = 31,
                            ProductId = 7,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 35,
                            IngredientId = 4,
                            ProductId = 8,
                            Quantity = 60m
                        },
                        new
                        {
                            Id = 36,
                            IngredientId = 12,
                            ProductId = 8,
                            Quantity = 20m
                        },
                        new
                        {
                            Id = 37,
                            IngredientId = 30,
                            ProductId = 8,
                            Quantity = 0.5m
                        },
                        new
                        {
                            Id = 38,
                            IngredientId = 5,
                            ProductId = 8,
                            Quantity = 25m
                        },
                        new
                        {
                            Id = 39,
                            IngredientId = 24,
                            ProductId = 8,
                            Quantity = 20m
                        },
                        new
                        {
                            Id = 40,
                            IngredientId = 1,
                            ProductId = 9,
                            Quantity = 60m
                        },
                        new
                        {
                            Id = 41,
                            IngredientId = 5,
                            ProductId = 9,
                            Quantity = 40m
                        },
                        new
                        {
                            Id = 42,
                            IngredientId = 6,
                            ProductId = 9,
                            Quantity = 10m
                        },
                        new
                        {
                            Id = 43,
                            IngredientId = 12,
                            ProductId = 9,
                            Quantity = 15m
                        },
                        new
                        {
                            Id = 44,
                            IngredientId = 9,
                            ProductId = 10,
                            Quantity = 40m
                        },
                        new
                        {
                            Id = 45,
                            IngredientId = 6,
                            ProductId = 10,
                            Quantity = 25m
                        },
                        new
                        {
                            Id = 46,
                            IngredientId = 12,
                            ProductId = 10,
                            Quantity = 20m
                        },
                        new
                        {
                            Id = 47,
                            IngredientId = 30,
                            ProductId = 10,
                            Quantity = 0.5m
                        },
                        new
                        {
                            Id = 48,
                            IngredientId = 24,
                            ProductId = 10,
                            Quantity = 60m
                        },
                        new
                        {
                            Id = 49,
                            IngredientId = 5,
                            ProductId = 10,
                            Quantity = 30m
                        },
                        new
                        {
                            Id = 50,
                            IngredientId = 1,
                            ProductId = 11,
                            Quantity = 200m
                        },
                        new
                        {
                            Id = 51,
                            IngredientId = 23,
                            ProductId = 11,
                            Quantity = 80m
                        },
                        new
                        {
                            Id = 52,
                            IngredientId = 12,
                            ProductId = 11,
                            Quantity = 40m
                        },
                        new
                        {
                            Id = 53,
                            IngredientId = 6,
                            ProductId = 11,
                            Quantity = 10m
                        },
                        new
                        {
                            Id = 54,
                            IngredientId = 9,
                            ProductId = 12,
                            Quantity = 250m
                        },
                        new
                        {
                            Id = 55,
                            IngredientId = 12,
                            ProductId = 12,
                            Quantity = 300m
                        },
                        new
                        {
                            Id = 56,
                            IngredientId = 30,
                            ProductId = 12,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 57,
                            IngredientId = 8,
                            ProductId = 12,
                            Quantity = 120m
                        },
                        new
                        {
                            Id = 58,
                            IngredientId = 17,
                            ProductId = 12,
                            Quantity = 40m
                        },
                        new
                        {
                            Id = 59,
                            IngredientId = 1,
                            ProductId = 12,
                            Quantity = 395m
                        },
                        new
                        {
                            Id = 60,
                            IngredientId = 6,
                            ProductId = 12,
                            Quantity = 30m
                        },
                        new
                        {
                            Id = 61,
                            IngredientId = 35,
                            ProductId = 12,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 62,
                            IngredientId = 1,
                            ProductId = 13,
                            Quantity = 790m
                        },
                        new
                        {
                            Id = 63,
                            IngredientId = 27,
                            ProductId = 13,
                            Quantity = 4m
                        },
                        new
                        {
                            Id = 64,
                            IngredientId = 30,
                            ProductId = 13,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 65,
                            IngredientId = 12,
                            ProductId = 13,
                            Quantity = 150m
                        },
                        new
                        {
                            Id = 66,
                            IngredientId = 6,
                            ProductId = 13,
                            Quantity = 60m
                        },
                        new
                        {
                            Id = 67,
                            IngredientId = 9,
                            ProductId = 13,
                            Quantity = 200m
                        },
                        new
                        {
                            Id = 68,
                            IngredientId = 35,
                            ProductId = 13,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 69,
                            IngredientId = 9,
                            ProductId = 14,
                            Quantity = 300m
                        },
                        new
                        {
                            Id = 70,
                            IngredientId = 12,
                            ProductId = 14,
                            Quantity = 350m
                        },
                        new
                        {
                            Id = 71,
                            IngredientId = 4,
                            ProductId = 14,
                            Quantity = 300m
                        },
                        new
                        {
                            Id = 72,
                            IngredientId = 6,
                            ProductId = 14,
                            Quantity = 150m
                        },
                        new
                        {
                            Id = 73,
                            IngredientId = 30,
                            ProductId = 14,
                            Quantity = 4m
                        },
                        new
                        {
                            Id = 74,
                            IngredientId = 26,
                            ProductId = 14,
                            Quantity = 15m
                        },
                        new
                        {
                            Id = 75,
                            IngredientId = 17,
                            ProductId = 14,
                            Quantity = 20m
                        },
                        new
                        {
                            Id = 76,
                            IngredientId = 3,
                            ProductId = 14,
                            Quantity = 200m
                        },
                        new
                        {
                            Id = 77,
                            IngredientId = 35,
                            ProductId = 14,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 78,
                            IngredientId = 9,
                            ProductId = 15,
                            Quantity = 600m
                        },
                        new
                        {
                            Id = 79,
                            IngredientId = 12,
                            ProductId = 15,
                            Quantity = 700m
                        },
                        new
                        {
                            Id = 80,
                            IngredientId = 6,
                            ProductId = 15,
                            Quantity = 400m
                        },
                        new
                        {
                            Id = 81,
                            IngredientId = 30,
                            ProductId = 15,
                            Quantity = 8m
                        },
                        new
                        {
                            Id = 82,
                            IngredientId = 5,
                            ProductId = 15,
                            Quantity = 500m
                        },
                        new
                        {
                            Id = 83,
                            IngredientId = 20,
                            ProductId = 15,
                            Quantity = 400m
                        },
                        new
                        {
                            Id = 84,
                            IngredientId = 24,
                            ProductId = 15,
                            Quantity = 300m
                        },
                        new
                        {
                            Id = 85,
                            IngredientId = 35,
                            ProductId = 15,
                            Quantity = 1m
                        });
                });

            modelBuilder.Entity("RecipeCosting.Api.Models.Entities.ProductLine", b =>
                {
                    b.HasOne("RecipeCosting.Api.Models.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecipeCosting.Api.Models.Entities.Product", "Product")
                        .WithMany("Lines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RecipeCosting.Api.Models.Entities.Product", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
