// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecipeCosting.Api.Data;

#nullable disable

namespace RecipeCosting.Api.Data.Migrations
{
    [DbContext(typeof(RecipeCostingDbContext))]
    partial class RecipeCostingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipeCosting.Api.Models.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<decimal>("PackagePrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("package_price");

                    b.Property<decimal>("PackageSize")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("package_size");

                    b.Property<int>("PackageUnit")
                        .HasColumnType("integer")
                        .HasColumnName("package_unit");

                    b.HasKey("Id");

                    b.ToTable("ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Condensed milk",
                            PackagePrice = 7.49m,
                            PackageSize = 395m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Table cream",
                            PackagePrice = 4.29m,
                            PackageSize = 200m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Whole milk",
                            PackagePrice = 5.49m,
                            PackageSize = 1000m,
                            PackageUnit = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cream cheese",
                            PackagePrice = 9.9m,
                            PackageSize = 150m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Whipping cream",
                            PackagePrice = 28.9m,
                            PackageSize = 1000m,
                            PackageUnit = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Unsalted butter",
                            PackagePrice = 12.9m,
                            PackageSize = 200m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Baking margarine",
                            PackagePrice = 9.9m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Vegetable oil",
                            PackagePrice = 8.49m,
                            PackageSize = 900m,
                            PackageUnit = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "All-purpose flour",
                            PackagePrice = 5.79m,
                            PackageSize = 1000m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cornstarch",
                            PackagePrice = 6.49m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cornmeal",
                            PackagePrice = 4.19m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Granulated sugar",
                            PackagePrice = 4.89m,
                            PackageSize = 1000m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Icing sugar",
                            PackagePrice = 5.29m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Brown sugar",
                            PackagePrice = 8.9m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "Glucose syrup",
                            PackagePrice = 12.5m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "Honey",
                            PackagePrice = 18.9m,
                            PackageSize = 250m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "Cocoa powder",
                            PackagePrice = 14.9m,
                            PackageSize = 200m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 18,
                            Name = "Semisweet chocolate",
                            PackagePrice = 42.9m,
                            PackageSize = 1000m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 19,
                            Name = "Milk chocolate",
                            PackagePrice = 44.9m,
                            PackageSize = 1000m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 20,
                            Name = "White chocolate",
                            PackagePrice = 46.5m,
                            PackageSize = 1000m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 21,
                            Name = "Roasted peanuts",
                            PackagePrice = 14.9m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 22,
                            Name = "Walnut halves",
                            PackagePrice = 19.9m,
                            PackageSize = 100m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 23,
                            Name = "Grated coconut",
                            PackagePrice = 6.9m,
                            PackageSize = 100m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 24,
                            Name = "Strawberries",
                            PackagePrice = 12.9m,
                            PackageSize = 300m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 25,
                            Name = "Vanilla extract",
                            PackagePrice = 18.9m,
                            PackageSize = 100m,
                            PackageUnit = 2
                        },
                        new
                        {
                            Id = 26,
                            Name = "Red food colouring",
                            PackagePrice = 7.9m,
                            PackageSize = 30m,
                            PackageUnit = 2
                        },
                        new
                        {
                            Id = 27,
                            Name = "Lemon",
                            PackagePrice = 9.6m,
                            PackageSize = 12m,
                            PackageUnit = 3
                        },
                        new
                        {
                            Id = 28,
                            Name = "Chocolate sprinkles",
                            PackagePrice = 13.9m,
                            PackageSize = 500m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 29,
                            Name = "Confetti sprinkles",
                            PackagePrice = 8.4m,
                            PackageSize = 100m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 30,
                            Name = "Eggs",
                            PackagePrice = 24.9m,
                            PackageSize = 30m,
                            PackageUnit = 3
                        },
                        new
                        {
                            Id = 31,
                            Name = "Baking powder",
                            PackagePrice = 4.19m,
                            PackageSize = 100m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 32,
                            Name = "Unflavoured gelatin",
                            PackagePrice = 5.9m,
                            PackageSize = 24m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 33,
                            Name = "Fine salt",
                            PackagePrice = 3.29m,
                            PackageSize = 1000m,
                            PackageUnit = 1
                        },
                        new
                        {
                            Id = 34,
                            Name = "Cupcake liners",
                            PackagePrice = 9.9m,
                            PackageSize = 100m,
                            PackageUnit = 3
                        },
                        new
                        {
                            Id = 35,
                            Name = "Cake box 20 cm",
                            PackagePrice = 24.0m,
                            PackageSize = 10m,
                            PackageUnit = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
